### PR TITLE
Add interface support for opens, closes, and assignments

### PR DESCRIPTION
**Pull request by bobjflong**
We recently added support for assigning, opening, and closing conversations: https://doc.intercom.io/api/#replying-to-a-conversation

We've also released updated versions of the Go, Java, Ruby, and PHP libraries. Be good to get nice support in here too!

### CODE REVIEW

**Comment by bobjflong** [comment]
Seems like the coveralls doesn't check for integration specs (which is where the other conversations specs seemed to be located)

**Comment by jkeyes** [comment]
Having a look at this now @bobjflong. Thanks.

**Comment by jkeyes** [comment]
@bobjflong The integration tests run against the real API, that's why you need to specify the `APP_ID` and the `API_KEY` before running them. That's why they don't run as part of the Travis build and therefore coveralls can't see the coverage results.

**Comment by jkeyes** [comment]
@bobjflong The integration tests are to mirror the functionality covered in the README. It's really the sanity test for the library, and allows us to check that the Intercom side is behaving as documented.

**Comment by bobjflong** [comment]
Hi @jkeyes thanks - is there anything I should do his to get this merge-able?

**Comment by jkeyes** [comment]
@bobjflong I'll merge it as is. I've work to do on version 3 which will bring it into line with the current intercom-ruby, and I'll move things around as need be then. Did a customer request this?

**Comment by bobjflong** [comment]
@jkeyes it's definitely been a commonly requested set of features, and quite popular since launch.

**Pull request merged**
